keys = ['created_at',
           'id',
           'id_str',
           'text',
           'source',
           'favorite_count',
            'coordinates',
            'place',
           'truncated',
           'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id',
           'in_reply_to_user_id_str', 'in_reply_to_screen_name',
           'user',
           'geo',
           'coordinates',
           'place',
           'contributors', 'is_quote_status', 'extended_tweet', 'quote_count',
           'reply_count', 'retweet_count',
           'entities', 'favorited', 'retweeted', 'filter_level', 'lang', 'timestamp_ms']
print(keys)
